[package]
name = "bl808-m0-led"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bl808-pac = { version = "0.1.0", path = "../bl808-pac", features = ["rt"]}
panic-halt = "0.2.0"
riscv-rt = "0.11.0"
